//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_assigments
    {
        public int assignmentId { get; set; }
        public Nullable<int> clientId { get; set; }
        public Nullable<int> therapistTypeId { get; set; }
        public Nullable<int> therapistId { get; set; }
        public Nullable<int> supervisorId { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    }
}
