//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class director
    {
        public int directorId { get; set; }
        public string directorFirstName { get; set; }
        public string directorMiddleName { get; set; }
        public string directorLastName { get; set; }
    }
}
