//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public int geostateid { get; set; }
        public string statenameshort { get; set; }
        public string statenamelong { get; set; }
        public int countryid { get; set; }
    }
}
