//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tax_types
    {
        public int taxtypeid { get; set; }
        public string taxtype { get; set; }
    }
}
