//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class therapist
    {
        public int therapistId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string middleName { get; set; }
        public string companyName { get; set; }
        public string therapistLevel { get; set; }
        public Nullable<int> therapistTaxType { get; set; }
        public Nullable<int> therapistType { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string education { get; set; }
        public Nullable<int> gender { get; set; }
        public string ssn { get; set; }
        public string languages { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<int> state { get; set; }
        public string zip { get; set; }
        public Nullable<int> country { get; set; }
        public Nullable<System.DateTime> hiredate { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> supervisorId { get; set; }
        public Nullable<System.DateTime> terminationdate { get; set; }
        public string password { get; set; }
        public string fein { get; set; }
        public string npi { get; set; }
        public string license { get; set; }
        public string provider { get; set; }
    }
}
