//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class therapist_requirements_types
    {
        public int requirementId { get; set; }
        public string requirementName { get; set; }
        public int requirementValidPeriodMonths { get; set; }
    }
}
