//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class therapist_rates
    {
        public int rateId { get; set; }
        public int therapistId { get; set; }
        public System.DateTime startDate { get; set; }
        public string endDate { get; set; }
        public decimal rateValue { get; set; }
        public int setByUserId { get; set; }
        public int rateType { get; set; }
        public Nullable<int> documentId { get; set; }
    }
}
