//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class therapist_requirements
    {
        public int therapistRequirementId { get; set; }
        public Nullable<bool> exempt { get; set; }
        public Nullable<bool> received { get; set; }
        public Nullable<System.DateTime> dateUpdated { get; set; }
        public byte[] datafile { get; set; }
        public string fileformat { get; set; }
        public Nullable<System.DateTime> expiresOn { get; set; }
        public int requirementTypeId { get; set; }
        public int therapistId { get; set; }
    }
}
